In [228]:
import keras
from keras import layers
import tensorflow as tf

In [247]:
layer = layers.Dense(8, activation='tanh', use_bias=True, kernel_initializer="zeros" ,bias_initializer="normal")
inputs = keras.random.uniform(shape=(4, 1))
outputs = layer(inputs)

In [255]:
layerbias = layers.Dense(8, activation='sigmoid', use_bias=True, kernel_initializer="zeros" ,bias_initializer="normal")
outputsbias = layerbias(inputs)

In [249]:
inputs

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.8019563 ],
       [0.5712457 ],
       [0.21691847],
       [0.72225225]], dtype=float32)>

In [231]:
layer.kernel

<Variable path=dense_39/kernel, shape=(1, 8), dtype=float32, value=[[0. 0. 0. 0. 0. 0. 0. 0.]]>

In [250]:
layer.bias

<Variable path=dense_42/bias, shape=(8,), dtype=float32, value=[-0.03746943 -0.07760812  0.08437568  0.01911549 -0.12254765 -0.02251194
 -0.01906243 -0.02735574]>

In [261]:
layerbias.bias

<Variable path=dense_44/bias, shape=(8,), dtype=float32, value=[ 0.05972178  0.07743753 -0.06123923 -0.03116894  0.01043782 -0.00757878
  0.02038895  0.02056398]>

In [260]:
layer.weights

[<Variable path=dense_42/kernel, shape=(1, 8), dtype=float32, value=[[0. 0. 0. 0. 0. 0. 0. 0.]]>,
 <Variable path=dense_42/bias, shape=(8,), dtype=float32, value=[-0.03746943 -0.07760812  0.08437568  0.01911549 -0.12254765 -0.02251194
  -0.01906243 -0.02735574]>]

In [256]:
outputs

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[-0.0374519 , -0.07745268,  0.08417601,  0.01911316, -0.12193785,
        -0.02250814, -0.01906012, -0.02734892],
       [-0.0374519 , -0.07745268,  0.08417601,  0.01911316, -0.12193785,
        -0.02250814, -0.01906012, -0.02734892],
       [-0.0374519 , -0.07745268,  0.08417601,  0.01911316, -0.12193785,
        -0.02250814, -0.01906012, -0.02734892],
       [-0.0374519 , -0.07745268,  0.08417601,  0.01911316, -0.12193785,
        -0.02250814, -0.01906012, -0.02734892]], dtype=float32)>

In [263]:
import numpy as np
import math

In [268]:
layer.bias

<Variable path=dense_42/bias, shape=(8,), dtype=float32, value=[-0.03746943 -0.07760812  0.08437568  0.01911549 -0.12254765 -0.02251194
 -0.01906243 -0.02735574]>

In [267]:
for arr in outputs :
    for val in arr :
        print(math.atan(val))


-0.03743440469184386
-0.0772983596114443
0.08397803981250183
0.019110833751694707
-0.12133882560407488
-0.022504337087241536
-0.01905781610805073
-0.02734209951312345
-0.03743440469184386
-0.0772983596114443
0.08397803981250183
0.019110833751694707
-0.12133882560407488
-0.022504337087241536
-0.01905781610805073
-0.02734209951312345
-0.03743440469184386
-0.0772983596114443
0.08397803981250183
0.019110833751694707
-0.12133882560407488
-0.022504337087241536
-0.01905781610805073
-0.02734209951312345
-0.03743440469184386
-0.0772983596114443
0.08397803981250183
0.019110833751694707
-0.12133882560407488
-0.022504337087241536
-0.01905781610805073
-0.02734209951312345


In [258]:
outputsbias

<tf.Tensor: shape=(4, 8), dtype=float32, numpy=
array([[0.51492596, 0.51934975, 0.48469496, 0.4922084 , 0.5026094 ,
        0.49810532, 0.50509703, 0.50514084],
       [0.51492596, 0.51934975, 0.48469496, 0.4922084 , 0.5026094 ,
        0.49810532, 0.50509703, 0.50514084],
       [0.51492596, 0.51934975, 0.48469496, 0.4922084 , 0.5026094 ,
        0.49810532, 0.50509703, 0.50514084],
       [0.51492596, 0.51934975, 0.48469496, 0.4922084 , 0.5026094 ,
        0.49810532, 0.50509703, 0.50514084]], dtype=float32)>

In [235]:
import numpy as np

In [236]:
kernel_input = np.dot(inputs, layer.kernel)
result_output = kernel_input + layer.bias 


C:\Users\alexandre.karneff\AppData\Local\Temp\ipykernel_17748\4201286966.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  kernel_input = np.dot(inputs, layer.kernel)


In [237]:
kernel_input

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [238]:
result_output

array([[0.1155257 , 0.08894878, 0.07998636, 0.01470164, 0.12388743,
        0.00463803, 0.01660339, 0.07016978],
       [0.1155257 , 0.08894878, 0.07998636, 0.01470164, 0.12388743,
        0.00463803, 0.01660339, 0.07016978],
       [0.1155257 , 0.08894878, 0.07998636, 0.01470164, 0.12388743,
        0.00463803, 0.01660339, 0.07016978],
       [0.1155257 , 0.08894878, 0.07998636, 0.01470164, 0.12388743,
        0.00463803, 0.01660339, 0.07016978]], dtype=float32)

In [269]:
from keras.models import Sequential

In [270]:
model = Sequential()

In [271]:
layer_1 = layers.Dense(1, activation='relu', use_bias=True, kernel_initializer="normal" ,bias_initializer="normal")
layer_2 = layers.Dense(2, activation='relu', use_bias=True, kernel_initializer="normal" ,bias_initializer="normal")
inputs_2 = keras.random.normal(shape=(4, 1))


In [272]:
model.add(layer_1)
model.add(layer_2)

In [273]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_45 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [274]:
outputs_2 = model(inputs_2)

In [275]:
model.weights

[<Variable path=sequential_8/dense_45/kernel, shape=(1, 1), dtype=float32, value=[[-0.01121981]]>,
 <Variable path=sequential_8/dense_45/bias, shape=(1,), dtype=float32, value=[0.08994154]>,
 <Variable path=sequential_8/dense_46/kernel, shape=(1, 2), dtype=float32, value=[[-0.00657336  0.02780797]]>,
 <Variable path=sequential_8/dense_46/bias, shape=(2,), dtype=float32, value=[-0.02348187  0.03684137]>]

In [276]:
outputs_2

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.        , 0.03953834],
       [0.        , 0.03943127],
       [0.        , 0.03921919],
       [0.        , 0.03976502]], dtype=float32)>